# $FreeBSD: head/net-p2p/bitmark-cli/Makefile 523293 2020-01-17 10:46:13Z araujo $

MASTERDIR=	${.CURDIR}/../bitmark
PKGNAMESUFFIX=	-cli

COMMENT=	Bitmark distributed property system cli

CONFLICTS?=	bitmark
SLAVE_PORT=	yes

OPTIONS_DEFINE=		CLI
OPTIONS_DEFAULT=	CLI

.include "${MASTERDIR}/Makefile"
