# $FreeBSD$

MASTERDIR=	${.CURDIR}/../bitmark
PKGNAMESUFFIX=	-cli

COMMENT=	Bitmark distributed property system cli
S
LAVE_PORT=	yes

OPTIONS_DEFINE=		CLI
OPTIONS_DEFAULT=	CLI

.include "${MASTERDIR}/Makefile"
